apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dt 
  janus-idp.io/tekton: dt
  backstage.io/kubernetes-id: dt
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dt
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  