apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dt 
  name: dt
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dt
    weight: 100 
